### ISSUE TITLE
model.generate() with inputs_embeds

### ISSUE THREAD

**Issue by ZhaoxuanWu** [BlackSamorez/tensor_parallel#112]
Hi! A very easy-to-use library.

When I call ``model.generate(inputs_embeds=...)`` with ``inputs_embeds`` instead of ``input_ids``, it does not seem to have been implemented.

```
*** ValueError: You passed `inputs_embeds` to `.generate()`, but the model class TensorParallelPreTrainedModel doesn't have its forwarding implemented. See the GPT2 implementation for an example (https://github.com/huggingface/transformers/pull/21405), and feel free to open a PR with it!
```

Can we have this feature? Thank you!

**Comment by BlackSamorez** [comment]
It looks like `transformers` relies of forward pass signature inspection to determine whether it's okay to use ```inputs_embeds```. Since `TensorParallelPreTrainedModel`'s forward's signature is `(self, *args, **kwargs)`, it becomes a false negative. I'll try and think of a workaround.
```python
has_inputs_embeds_forwarding = "inputs_embeds" in set(
    inspect.signature(self.prepare_inputs_for_generation).parameters.keys()
)
```

**Comment by BlackSamorez** [comment]
Working on it in #113

**Comment by ZhaoxuanWu** [comment]
It works like a charm. Many thanks!
