### ISSUE TITLE
Support of 8-bit and 4-bit quantization

### ISSUE THREAD

**Issue by ludwigflo** [BlackSamorez/tensor_parallel#119]
Hey, 
first of all thank you for your effort in building this library! Is it possible to combine tensor_parallel with new quantization techniques like 8-bit or 4-bit quantization (e.g. BitsAndBytes or GPTQ). This would be really useful, especially when it comes to Large language models like Llama2-70B. I think there will be a huge request on this topic!
Thank you again and best regards :)

**Comment by BlackSamorez** [comment]
It is supported. See [this demo](https://www.kaggle.com/code/blacksamorez/tensor-parallel-int4-llm/).
