### ISSUE TITLE
Feature request: revert tensor_parallel model back into normal state_dict

### ISSUE THREAD

**Issue by justheuristic** [BlackSamorez/tensor_parallel#21]
It would be nice to export a tensor-parallel model in such a way that its state can be loaded with a different number of ranks. Something like

```
model = tp.tensor_parallel(model)
restored_model = tp.undo_tensor_parallel(model, output_device='cpu')
torch.save(restored_model.state_dict())
```

**Comment by BlackSamorez** [comment]
Done in [v1.1.4](https://github.com/BlackSamorez/tensor_parallel/releases/tag/v1.1.4) in a form of context wrapper:
```
with tp.save_tensor_parallel(model):
    torch.save(model.state_dict(), "/tmp/")
```
