### ISSUE TITLE
Example: finetune T5-XXL or mT5-XXL with prompt-tuning or similar

### ISSUE THREAD

**Issue by justheuristic** [BlackSamorez/tensor_parallel#23]
- [x] depends on: #14 
- [x] pre-process (shard) T5 checkpoint so that it can be loaded into kaggle
   - [x] make sure you keep the pre-processing script or save a link to that for the readers!
- [x] push sharded model to HF
- [x] write a LoRA or prefix-tuning or IA3 wrapper for T5 or use adapter_transformers
- [x] train the model on something funny

**Comment by justheuristic** [comment]
Loaded pre-sharded xxl model by @younesbelkada, seems to work

![image](https://user-images.githubusercontent.com/3491902/209467711-0bc8469f-97d4-4fb1-a571-f1cd231f65ab.png)

**Comment by BlackSamorez** [comment]
With `tensor_parallel.convert_state_dict` no checkpoint conversion is needed anymore. Checking it out.

**Comment by BlackSamorez** [comment]
Done in the [latest kaggle demo](https://www.kaggle.com/code/blacksamorez/tensor-parallel-int8-llm/) using [BitsAndBytes](https://github.com/TimDettmers/bitsandbytes) and [PEFT](https://huggingface.co/blog/peft) with LORA adapters.
A selection of models is present including:
* GPT-NeoXT-Chat-Base-20B
* flan-ul2
* codegen-16B-multi
