### ISSUE TITLE
set distributed=True, return AttributeError: 'NoneType' object 

### ISSUE THREAD

**Issue by rocketsearch** [BlackSamorez/tensor_parallel#69]
For example: 

tp.tensor_parallel(module=model, device_ids=["cuda:0", "cuda:1"], distributed=True) 
-----
AttributeError: 'NoneType' object has no attribute 'make_distributed_shard'

**Comment by BlackSamorez** [comment]
@rocketsearch Good morning!
I've released version 1.2.2 which is supposed to fix this issue.
Distributed functionality hasn't been properly tested in a long time, so it was plain broken. I'm planning to write test for it sometime later.

**Comment by rocketsearch** [comment]
Thanks
