### ISSUE TITLE
What is the difference between this project and autotp of deepspeed?

### ISSUE THREAD

**Issue by frankxyy** [BlackSamorez/tensor_parallel#72]
It seems that in deepspeed there is an auto tensor parallel scheme to use.

**Comment by BlackSamorez** [comment]
`tensor_parallel` has a few distinct features compared to deepspeed:
 * It works with any *PyTorch* model out of the box. From what I've seen, [deepspeed Automatic Tensor Parallelism](https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/) only works for a selection of Hugging Face models.
 * It works in an interactive environment in a *Jupyter Notebook*. Deepspeed doesn't.
 * It supports training. I haven't been able to find whether [deepspeed Automatic Tensor Parallelism](https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/) does.
