### ISSUE TITLE
Torch version requirement

### ISSUE THREAD

**Issue by treya-lin** [BlackSamorez/tensor_parallel#76]
Hi may I know the environmental requirement of this tool? 

I have torch1.9-cu111 installed locally, but when I tried to install this tool, it automatically installed torch1.13 and uninstalled the original torch1.9. 

And earlier there was another time when I have torch1.12-cu102 installed in advance and installed tensor-parallel afterwards, and it seems happy with torch 1.12. 

So what is the minimum requirement of it? Having a hard time to work around all the  compatibility thing amid torch/cuda/etc ....

**Comment by treya-lin** [comment]
> @treya-lin Hi! Latest [peft](https://github.com/huggingface/peft) requires `torch>=1.13.0`. This library requires latest peft. If you aren't using peft you could probably ignore this dependency. Actually I should probably make it optional and add runtime checks for peft imports since it's not needed for core functionality.

Hi Thanks for the explanation! And FYI tensor-parallel==1.2.2 was installed properly in my torch1.12.1 enverionment without asking for torch 1.13 (I used pip install).  Is tensor-parallel 1.2.2 working with a different version of peft that does not require torch to be as high as 1.13.0?

**Comment by BlackSamorez** [comment]
> > @treya-lin Hi! Latest [peft](https://github.com/huggingface/peft) requires `torch>=1.13.0`. This library requires latest peft. If you aren't using peft you could probably ignore this dependency. Actually I should probably make it optional and add runtime checks for peft imports since it's not needed for core functionality.
> 
> Hi Thanks for the explanation! And FYI for now I am working in an environment where tensor-parallel==1.2.2 was installed properly with torch1.12.1 enverionment asking for torch 1.13 (I used pip install). Is tensor-parallel 1.2.2 working with a different version of peft that does not require torch to be as high as 1.13.0?

The support for `peft` was added in [v1.2.3](https://github.com/BlackSamorez/tensor_parallel/releases/tag/v1.2.3). The requirement wasn't there until that.

**Comment by treya-lin** [comment]
> > > @treya-lin Hi! Latest [peft](https://github.com/huggingface/peft) requires `torch>=1.13.0`. This library requires latest peft. If you aren't using peft you could probably ignore this dependency. Actually I should probably make it optional and add runtime checks for peft imports since it's not needed for core functionality.
> > 
> > 
> > Hi Thanks for the explanation! And FYI for now I am working in an environment where tensor-parallel==1.2.2 was installed properly with torch1.12.1 enverionment asking for torch 1.13 (I used pip install). Is tensor-parallel 1.2.2 working with a different version of peft that does not require torch to be as high as 1.13.0?
> 
> The support for `peft` was added in [v1.2.3](https://github.com/BlackSamorez/tensor_parallel/releases/tag/v1.2.3). The requirement wasn't there until that.

Oh I see! Thank you.
