### ISSUE TITLE
Possibility to run on different GPUs

### ISSUE THREAD

**Issue by Ch4mpa9ne** [BlackSamorez/tensor_parallel#94]
Is it possible to run this on multiple different models of GPUs?

Given the goal of minimizing GPU costs as much as possible, I can only choose between a GPU with large VRAM and low performance or a GPU with high performance and low VRAM. Would it be possible to purchase both types of GPUs, one with large VRAM and low performance and the other with high performance and low VRAM, and perform parallel inference using them? Could this potentially help improve inference speed to some extent while still obtaining the large VRAM required to run large models?

**Comment by BlackSamorez** [comment]
It's possible to run on different GPUs, but the performance will be determined by the slowest GPU used, leaving the fast one underutilized. So in your case there is no point in using a slow and a fast GPU for tensor parallelism.

**Comment by Ch4mpa9ne** [comment]
thanks
